openapi: '3.0.2'
info:
  title: Hacker News
  version: '1.0'
  description: hola
servers:
  - url: http://[::1]:3000/
  - url: https://hidden-earth-40420.herokuapp.com/

components:
  schemas:
    Submission:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: identificador d'una submission
          example: 2
        title:
          type: string
          description: titol d'una submission
          example: 'Titol'
        url:
          type: string
          description: url d'una submission
          example: 'https://google.com'
        text:
          type: string
          description: text d'una submission
          example: 'comentari'
        user_id:
          type: integer
          format: int64
          description: identificador de l'usuari creador de la submission
          example: 1
        created_at:
          type: string
          format: date-time
          description: data de creació 
          example: 2021-11-26T09:33:27.238Z
        udpated_at:
          type: string
          format: date-time
          description: data de la darrera modificacio
          example: 2011-12-26T09:33:27.238Z
        upVotes:
          type: integer
          format: int64
          description: nombre de vots
          example: 2

    SubmissionPost:
      type: object
      properties:
        title:
          type: string
          description: titol d'una submission
          example: 'Titol'
        url:
          type: string
          description: url d'una submission
          example: 'https://google.com'
        text:
          type: string
          description: text d'una submission
          example: 'comentari'

    User:
      type: object
      properties:
        username:
          type: string
          description: "Nom de l'usuari"
          example: "Adria"
        email:
          type: string
          description: "Email de l'usuari"
          example: "adria.garcia.fernandez@estudiantat.upc.edu"
        password_digest:
          type: string
          description: "Contrassenya encriptada"
          example: "$2a$12$Uqdgpfe3aAWNUS.koeHJkuml75Mgd8.xWAj5CTodctOZ8EF1cVKG6"
        uid:
          type: string
          description: "ID generada automàtica"
          example: "101001275528432852910"
        provider:
          type: string
          description: "Proveïdor del login"
          example: "google_oauth2"
        created_at:
          type: string
          description: "Data de creació de l'usuari"
          example: "2021-11-17T22:35:11.636Z"
        updated_at:
          type: string
          description: "Data d'última modificació de l'usuari"
          example: "2021-11-17T22:35:11.636Z"
        about:
          type: string
          description: "Biografia de l'usuari"
          example: "Hello"
        token:
          type: string
          description: "Token de seguretat generat per Google"
          example:

    Comment:
      type: object
      properties:
        user_id:
          type: integer
          description: "ID de l'usuari"
          example: 
        submission_id:
          type: integer
          description: "ID de la submission"
          example: 1
        content:
          type: string
          description: "text del comentari"
          example: 'example'

    Createcomment:
      type: object
      properties:
        submission_id:
          type: integer
          description: "ID de la submission"
          example: 1
        content:
          type: string
          description: "text del comentari"
          example: 'example'
        parent_id:
          type: integer
          description: "ID del comentari pare"
          example: 1

    ErrorResult:
      type: object
      properties:
        status:
          type: integer
          enum: [400, 401, 403, 404, 409]
        error: 
          type: string
          enum: ["Bad Request", "Unauthorized", "Forbidden", "Not Found", "Conflict"]
        message: 
          type: string
  examples:
    error400:
      value:
        status: 400
        error: "Bad Request"
        message: "Algun dels camps és incorrecte"
    error401:
      value:
        status: 401
        error: "Unauthorized"
        message: "No s'ha proporcionat cap api key"
    error403:
      value:
        status: 403
        error: "Forbidden"
        message: "La teva api key (X-API-KEY Header) es invalida"
    error404:
      value:
        status: 404
        error: "Not Found"
        message: "Cap submission amb aquesta ID"
          
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X_API_KEY
      in: header


paths:
  /submissions:
    get:
      tags:
        - submissions
      summary: troba totes les submissions de tipus url
      description: retorna totes les submissions de tipus url ordenades per vots
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Submission'
    post: 
      tags: 
        - submissions
      summary: crea una nova submission
      requestBody:
        description: Omple el camp títol i url per fer una submission
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmissionPost'
        required: true
      responses:   
        '200':
          description: La submission amb aquesta url ja existeix
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Submission'
        '201':
          description: Submission creada
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Submission'
        '400':
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error400'
        '401':
          description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '403':
          description: 'Error: Forbbiden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error403'
      security:
        - ApiKeyAuth: []
  /ask:
    get:
      tags:
        - submissions
      summary: troba totes les submissions de tipus ask
      description: retorna totes les submissions de tipus ask ordenades per vots
      responses:
        '200':
          description: S'ha retornat la submission especificada.
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Submission'
  /newest:
    get:
      tags:
        - submissions
      summary: troba totes les submissions
      description: retorna totes les submissions de tipus ask ordenades per data de publicació
      responses:
        '200':
          description: S'ha retornat la submission especificada.
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Submission'

  /submissions/{submission_id}:
    get:
      tags:
        - submissions
      summary: troba una submission per id
      description: retorna una submission
      operationId: getSubmissionbyId
      parameters:
        - name: submission_id
          in: path
          description: Identificador de la publicació.
          required: true
          schema:
            type: integer
            format: int64
      responses:
          '200':
            description: S'ha retornat la submission especificada.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Submission'
          '404':
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'



  /submissions/{submission_id}/comments:
    get:
      tags:
      - submissions
      summary: Retorna tots els comentaris d'una submission.
      description: Retorna tots els comentaris d'una submission.
      parameters:
      - name: submission_id
        in: path
        description: ID de la submission.
        required: true
        schema:
          type: integer
          format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'

  /users/{user_id}:
    get:
      tags:
        - users
      summary: troba un usuari per id
      description: retorna un usuari
      operationId: getUserbyId
      parameters:
      - name: user_id
        in: path
        description: ID of User to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'

    put:
      tags:
      - users
      summary: Edita la informació about de l'usuari loguejat
      description: Edita la informació about de l'usuari loguejat
      parameters:
      - name: user_id
        in: path
        description: ID de l'usuari
        required: true
        schema:
          type: integer
          format: int
      requestBody:
        description: About que volem posar
        content:
          application/json:
            schema:
              required:
              - about
              type: object
              properties:
                about:
                  type: string
        required: true
      responses:
        200:
          description: Canvi fet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'  
      security:
          - ApiKeyAuth: []                
  
  /users/{user_id}/comments:
    get:
      tags:
        - users
      summary: troba un usuari per id i retorna els comentaris
      description: retorna els comentaris d'un usuari
      operationId: getUserCommentsbyId
      parameters:
      - name: user_id
        in: path
        description: ID of User to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'

  /users:
    get:
      tags:
        - users
      summary: troba tots els usuaris
      description: retorna un usuari
      operationId: getUsers
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /comments:
   post: 
      tags: 
        - comments
      summary: crea una nou comentari
      requestBody:
        description: Parametres del comentari
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Createcomment'
        required: true
      responses:   
        '201':
          description: comentari creat
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Comment'
        '400':
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error400'
        '401':
          description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '403':
          description: 'Error: Forbbiden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error403'
      security:
        - ApiKeyAuth: []

  /submissions/{submission_id}/upvote:
      post:
        tags:
          - submissions
        description: Vota la publicació amb id passada.
        parameters:
          - name: submission_id
            in: path
            description: Identificador de la publicació.
            required: true
            schema:
              type: integer
              format: int64
        responses:
          200:
            description: S'ha votat la publicació especificada amb l'usuari autenticat.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Submission'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
        security:
          - ApiKeyAuth: []

  /comments/{comment_id}/upvotec:
      post:
        tags:
          - comments
        description: Vota el comentari amb la id passada.
        parameters:
          - name: comment_id
            in: path
            description: Identificador del comentari.
            required: true
            schema:
              type: integer
              format: int64
        responses:
          200:
            description: S'ha votat la publicació especificada amb l'usuari autenticat.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Comment'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
        security:
          - ApiKeyAuth: []
    